global:
  scrape_interval: 30s
  evaluation_interval: 30s
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093
scrape_configs:
  - job_name: 'gaarf'
    honor_labels: true
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9091']

