groups:
  - name: googleads
    rules:
      - record: googleads:impressions:overall
        expr: sum(googleads_impressions)

      - record: googleads:conversions:overall
        expr: sum(googleads_conversions)

      - alert: NoAdsImpressions
        expr: deriv(googleads:impressions:overall[30m]) == 0
        for: 30m
        labels:
          severity: crucial
        annotations:
          summary: No Ads Impressions for the last 30 minutes

      - alert: NoAdsConversions
        expr: deriv(googleads:conversions:overall[30m]) == 0
        for: 1h
        labels:
          severity: crucial
        annotations:
          summary: No Ads Conversions for the last hour

      - alert: DoubleGDNCostCampaign
        expr: sum by(campaign_id) (googleads_cost{network="CONTENT"}) / sum by(campaign_id) (googleads_cost{network="CONTENT"} offset 30m) > 2.0 and (sum by(campaign_id) (googleads_cost) > 1)
        for: 1h
        labels:
          severity: high
          team: display

      - alert: DoubleSearchCostCampaign
        expr: sum by(campaign_id) (googleads_cost{network="SEARCH"}) / sum by(campaign_id) (googleads_cost{network="SEARCH"} offset 30m) > 2.0 and (sum by(campaign_id) (googleads_cost) > 1)
        for: 1h
        labels:
          severity: high
          team: search

      - alert: AdsNotReviewedForMoreThanOneDay
        expr: googleads_approvals_ad_count{review_status!="REVIEWED"} and on() hour() >= 3 <=15
        for: 1d
        labels:
          severity: medium
          domain: approvals
        annotations:
          summary: Some ads haven't been reviewed for more than 24 hours
          description: >
            Campaigns with unreviewed ads: {{ range query "googleads_approvals_ad_count{review_status!='REVIEWED'}" }}
              {{ .Labels.campaign_id }}
            {{ end }}


