groups:
  - name: gaarf
    rules:
      - record: gaarf:impressions:overall
        expr: sum(gaarf_impressions)

      - record: gaarf:conversions:overall
        expr: sum(gaarf_conversions)

      - alert: NoAdsImpressions
        expr: deriv(gaarf:impressions:overall[30m]) == 0
        for: 30m
        labels:
          severity: crucial
        annotations:
          summary: No Ads Impressions for the last 30 minutes

      - alert: NoAdsConversions
        expr: deriv(gaarf:conversions:overall[30m]) == 0
        for: 1h
        labels:
          severity: crucial
        annotations:
          summary: No Ads Conversions for the last hour

      - alert: DoubleGDNCostCampaign
        expr: sum by(campaign_id) (gaarf_cost{network="CONTENT"}) / sum by(campaign_id) (gaarf_cost{network="CONTENT"} offset 30m) > 2.0 and (sum by(campaign_id) (gaarf_cost) > 1)
        labels:
          severity: high
          team: display

      - alert: DoubleSearchCostCampaign
        expr: sum by(campaign_id) (gaarf_cost{network="SEARCH"}) / sum by(campaign_id) (gaarf_cost{network="SEARCH"} offset 30m) > 2.0 and (sum by(campaign_id) (gaarf_cost) > 1)
        labels:
          severity: high
          team: search

      - alert: AdsNotReviewedForMoreThanOneDay
        expr: gaarf_approvals_ad_count{review_status!="REVIEWED"} and on() hour() >= 3 <=15
        for: 1d
        labels:
          severity: medium
          domain: approvals
        annotations:
          summary: Some ads haven't been reviewed for more than 24 hours
          description: >
            Campaigns with unreviewed ads: {{ range query "gaarf_approvals_ad_count{review_status!='REVIEWED'}" }}
              {{ .Labels.campaign_id }}
            {{ end }}


